# Generated by Django 4.2.22 on 2025-06-09 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(choices=[('pazartesi', 'Pazartesi'), ('salı', 'Salı'), ('çarşamba', 'Çarşamba'), ('perşembe', 'Perşembe'), ('cuma', 'Cuma'), ('cumartesi', 'Cumartesi'), ('pazar', 'Pazar')], max_length=10, unique=True)),
                ('opening_hours', models.TimeField()),
                ('closing_hours', models.TimeField(default=datetime.time(0, 0))),
            ],
        ),
    ]
