# Generated by Django 4.2.22 on 2025-06-10 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklyschedule',
            options={'ordering': ['day']},
        ),
    ]
