# Generated by Django 4.2.22 on 2025-06-10 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='profile.jpg', upload_to='profile_images/'),
        ),
    ]
