# Generated by Django 5.2.2 on 2025-06-07 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='نام دسته بندی')),
                ('img', models.ImageField(upload_to='categories/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام غذا')),
                ('description', models.CharField(max_length=200, verbose_name='توضیحات')),
                ('img', models.ImageField(upload_to='foods/', verbose_name='تصویر')),
                ('price', models.IntegerField(verbose_name='قیمت')),
                ('rate', models.IntegerField(default=0, verbose_name='امتیاز')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('default_category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='foods', to='menu.category')),
            ],
            options={
                'verbose_name': 'غذا',
                'verbose_name_plural': 'غذا ها',
            },
        ),
    ]
